name:                heedless-db
version:             0.1.0.0
github:              "tchajed/heedless-db"
license:             BSD3
author:              "Tej Chajed"
maintainer:          "tchajed@mit.edu"
copyright:           "2018 Tej Chajed"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/tchajed/heedless-db#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
    - hashtables
    - hashable
    - array
    - bytestring
    - unix
    - unix-bytestring
    - cereal
    - mtl
    - filepath
    - directory
  ghc-options:
    - -Wno-name-shadowing

executables:
  heedless-db-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - heedless-db
    - optparse-applicative

tests:
  spec:
    defaults: hspec/hspec@master
    default-extensions:
    - OverloadedStrings
    dependencies:
    - heedless-db
    - bytestring
    - cereal
    - mtl
